# Generated by Django 6.0.2 on 2026-02-27 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0002_load_csl_2026_teams"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_time", models.DateTimeField(verbose_name="比赛时间")),
                ("round_number", models.PositiveIntegerField(verbose_name="轮次")),
                (
                    "stadium",
                    models.CharField(blank=True, max_length=100, verbose_name="场地"),
                ),
                (
                    "tickets_open",
                    models.BooleanField(default=False, verbose_name="已开票"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="teams.team",
                        verbose_name="客队",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="teams.team",
                        verbose_name="主队",
                    ),
                ),
            ],
            options={
                "verbose_name": "比赛",
                "verbose_name_plural": "比赛",
                "ordering": ["match_time"],
            },
        ),
    ]
