# Generated by Django 6.0.2

from datetime import datetime, timedelta
from django.db import migrations
from django.utils import timezone


def generate_schedule(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    Match = apps.get_model("matches", "Match")

    short_names = [
        "上海海港", "上海申花", "成都蓉城", "北京国安", "山东泰山", "天津津门虎",
        "浙江", "云南玉昆", "青岛西海岸", "河南", "大连英博", "深圳新鹏城",
        "武汉三镇", "青岛海牛", "辽宁铁人", "重庆铜梁龙",
    ]
    teams = [Team.objects.get(short_name=name) for name in short_names]
    n = len(teams)

    # 轮次日期：2026年3月6日起，每轮间隔约7天
    base_date = datetime(2026, 3, 6, 19, 35, 0)
    base_date = timezone.make_aware(base_date)

    # 第一循环15轮：标准轮转
    first_half = []
    for r in range(n - 1):
        round_matches = []
        for i in range(n // 2):
            home_idx, away_idx = i, n - 1 - i
            round_matches.append((teams[home_idx], teams[away_idx]))
        first_half.append(round_matches)
        # 轮转：0固定，其余顺时针
        teams = [teams[0]] + [teams[-1]] + teams[1:-1]

    # 第二循环15轮：主客对调
    second_half = []
    for round_matches in first_half:
        second_half.append([(a, h) for h, a in round_matches])

    all_rounds = first_half + second_half
    time_offsets = [0, 1, 2, 3, 4, 5, 6, 7]  # 同轮内错开时间（小时）

    for round_num, round_matches in enumerate(all_rounds, 1):
        round_date = base_date + timedelta(days=(round_num - 1) * 7)
        for i, (home, away) in enumerate(round_matches):
            match_time = round_date + timedelta(hours=time_offsets[i % 8])
            stadium = home.stadium or ""
            Match.objects.create(
                home_team=home,
                away_team=away,
                match_time=match_time,
                round_number=round_num,
                stadium=stadium,
                tickets_open=False,
            )


def reverse_schedule(apps, schema_editor):
    Match = apps.get_model("matches", "Match")
    Match.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
        ("teams", "0002_load_csl_2026_teams"),
    ]

    operations = [
        migrations.RunPython(generate_schedule, reverse_schedule),
    ]
