# Generated by Django 6.0.2 on 2026-02-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="球队全称")),
                ("short_name", models.CharField(max_length=50, verbose_name="简称")),
                ("city", models.CharField(max_length=50, verbose_name="所在城市")),
                (
                    "stadium",
                    models.CharField(blank=True, max_length=100, verbose_name="主场"),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="成立年份"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "球队",
                "verbose_name_plural": "球队",
                "ordering": ["name"],
            },
        ),
    ]
