# Generated by Django 6.0.2 on 2026-02-26 16:23

from django.db import migrations


def load_teams(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    teams_data = [
        ("上海海港足球俱乐部", "上海海港", "上海", "上汽浦东球场", 2005),
        ("上海申花足球俱乐部", "上海申花", "上海", "上海体育场", 1993),
        ("成都蓉城足球俱乐部", "成都蓉城", "成都", "五粮液文化体育中心", 2018),
        ("北京国安足球俱乐部", "北京国安", "北京", "北京工人体育场", 1992),
        ("山东泰山足球俱乐部", "山东泰山", "济南", "济南奥体中心", 1993),
        ("天津津门虎足球俱乐部", "天津津门虎", "天津", "天津泰达足球场", 1998),
        ("浙江职业足球俱乐部", "浙江", "杭州", "浙江黄龙体育中心", 1998),
        ("云南玉昆足球俱乐部", "云南玉昆", "昆明", "玉溪高原体育运动中心", 2022),
        ("青岛西海岸足球俱乐部", "青岛西海岸", "青岛", "青岛西海岸大学城体育场", 2007),
        ("河南足球俱乐部", "河南", "郑州", "郑州航海体育场", 1994),
        ("大连英博足球俱乐部", "大连英博", "大连", "大连梭鱼湾足球场", 2009),
        ("深圳新鹏城足球俱乐部", "深圳新鹏城", "深圳", "深圳市体育中心体育场", 2016),
        ("武汉三镇足球俱乐部", "武汉三镇", "武汉", "武汉体育中心", 2013),
        ("青岛海牛足球俱乐部", "青岛海牛", "青岛", "青岛青春足球场", 1993),
        ("辽宁铁人足球俱乐部", "辽宁铁人", "沈阳", "沈阳奥体中心", 1995),
        ("重庆铜梁龙足球俱乐部", "重庆铜梁龙", "重庆", "重庆铜梁龙体育场", 2021),
    ]
    for name, short_name, city, stadium, year in teams_data:
        Team.objects.create(
            name=name,
            short_name=short_name,
            city=city,
            stadium=stadium,
            founded_year=year,
        )


def reverse_load_teams(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    Team.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_teams, reverse_load_teams),
    ]
