# Generated by Django 6.0.2 on 2026-03-09 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_load_csl_2026_teams"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "position",
                    models.CharField(blank=True, max_length=20, verbose_name="位置"),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="球衣号码"
                    ),
                ),
                ("goals", models.PositiveIntegerField(default=0, verbose_name="进球")),
                (
                    "assists",
                    models.PositiveIntegerField(default=0, verbose_name="助攻"),
                ),
                (
                    "yellow_cards",
                    models.PositiveIntegerField(default=0, verbose_name="黄牌"),
                ),
                (
                    "red_cards",
                    models.PositiveIntegerField(default=0, verbose_name="红牌"),
                ),
                (
                    "penalties",
                    models.PositiveIntegerField(default=0, verbose_name="点球"),
                ),
                ("shots", models.PositiveIntegerField(default=0, verbose_name="射门")),
                (
                    "shots_on_target",
                    models.PositiveIntegerField(default=0, verbose_name="射正"),
                ),
                (
                    "dribbles",
                    models.PositiveIntegerField(default=0, verbose_name="过人"),
                ),
                ("fouls", models.PositiveIntegerField(default=0, verbose_name="犯规")),
                (
                    "fouls_suffered",
                    models.PositiveIntegerField(default=0, verbose_name="被犯规"),
                ),
                ("passes", models.PositiveIntegerField(default=0, verbose_name="传球")),
                (
                    "crosses",
                    models.PositiveIntegerField(default=0, verbose_name="传中"),
                ),
                (
                    "tackles",
                    models.PositiveIntegerField(default=0, verbose_name="抢断"),
                ),
                (
                    "clearances",
                    models.PositiveIntegerField(default=0, verbose_name="解围"),
                ),
                ("saves", models.PositiveIntegerField(default=0, verbose_name="扑救")),
                (
                    "market_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="身价（万元）",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="teams.team",
                        verbose_name="球队",
                    ),
                ),
            ],
            options={
                "verbose_name": "球员",
                "verbose_name_plural": "球员",
                "ordering": ["team", "number"],
            },
        ),
    ]
