# Generated by Django 6.0.2 on 2026-03-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="year",
            field=models.PositiveIntegerField(default=2026, verbose_name="年份"),
        ),
    ]
