# Generated by Django 6.0.2 on 2026-02-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "summary",
                    models.CharField(blank=True, max_length=300, verbose_name="摘要"),
                ),
                ("content", models.TextField(blank=True, verbose_name="内容")),
                (
                    "published_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "新闻",
                "verbose_name_plural": "新闻",
                "ordering": ["-published_at"],
            },
        ),
    ]
