# Generated by Django 6.0.2 on 2026-02-27 12:23

from django.db import migrations


def load_news(apps, schema_editor):
    News = apps.get_model("core", "News")
    news_data = [
        ("2026赛季中超3月6日开赛", "新赛季揭幕战成都蓉城主场迎战深圳新鹏城"),
        ("中超16支球队准入名单公布", "广西平果无缘新赛季"),
        ("九支球队因假赌黑整治被扣分", "新赛季将以负分开局"),
    ]
    for title, summary in news_data:
        News.objects.create(title=title, summary=summary)


def reverse_load_news(apps, schema_editor):
    News = apps.get_model("core", "News")
    News.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_news, reverse_load_news),
    ]
