# Generated by Django 6.0.2 on 2026-03-02 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_load_sample_news"),
        ("matches", "0002_load_csl_2026_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_price", models.PositiveIntegerField(verbose_name="票档价格")),
                (
                    "ticket_count",
                    models.PositiveIntegerField(default=1, verbose_name="购票张数"),
                ),
                ("id_card", models.CharField(max_length=18, verbose_name="身份证号")),
                ("phone", models.CharField(max_length=11, verbose_name="手机号")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总金额"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=32, unique=True, verbose_name="订单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "payment_qr_code",
                    models.TextField(blank=True, verbose_name="支付二维码数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matches.match",
                        verbose_name="比赛",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "购票订单",
                "verbose_name_plural": "购票订单",
                "ordering": ["-created_at"],
            },
        ),
    ]
