"""
Django settings for soccer_admin project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-x)mcr)8=-s5+g(y$09x2)f&0zo0%)vty!rj-!ud45i8oly766-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 足球赛事管理系统应用
    "core",
    "teams",
    "leagues",
    "matches",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "soccer_admin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    "core.backends.EmailAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]

WSGI_APPLICATION = "soccer_admin.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# ── 支付宝沙箱环境配置 ──
ALIPAY_APPID = "9021000162678789"
ALIPAY_GATEWAY = "https://openapi-sandbox.dl.alipaydev.com/gateway.do"
ALIPAY_APP_PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDRPNlFXp5VDlsK
O0M/5Dini/Npwfj4zpbz4OZgMuoFIWH8OJOw5fyqGK2KZ6ZeVKPs64ZhmnmhEqNX
LrvNRdlhJWOtzpfeySZiSbMPQoFDVfkmpzRHsc+94CFDBx4GLHO5t87OOlKhMuOj
G1uNeMxBkfw90chjYHlhFaQvV98zTGlrrZmHWgsN4SP1NlmcEie519HCW5Do3Saa
9J0JTYrb8BIEz6Jacm0c/j3V6HItoPohq4Za34IPF331+e+g0OfKOHpiIK/rGVdQ
L3N4Ru65r8F2Hb0U6d8HtJnwwnfm8dnv4zD/jSA4xCJXsps6xQWyla7SvcJy4XLh
YJgOyZf7AgMBAAECggEBAIF0yGjnFcdCTomSCRWqunLPYBb68HPgPf0+FMtINQpf
kSRgTOCSKzWCdzy+zGxoqdOYFVimHsLNqUnznDZxFQHKBFYxED3C7oC5YJP8bcWf
l7uWj/4bwZCU739tE+J19lPdqZJm+2DI/5aXApoRNy8Kh6on9Xem5PJwVVkFYQ93
BPn1i90QfBesZI5lb+dc/AW28hFMTIvtCaOlPucmqD8ndeOxmN0oWxqag2GOBWkW
mtSLIUr0sVAHhPh6TTZKab8vQSzs6j70YJ8ohHHCRAXF8jjsgtSG1639C1d7x/XT
INPXJ0Ra+EeGdqd1SiLq2nDFTivIjz0soCRAyb0nl2ECgYEA7PxcDqkjpAyk6HR/
jsA4Sj4KYlVzvrqkuhvVYMIptpB8TyhO5EO9eSTpgZbAanM4CxZIFkmoDPPlE3Vc
DO9A3tDBYAtde8RPALzrqrvuiezYuFMfdsTRypJSN/95M7BQ/y5fOLkWRD4Uy+/o
Xw9PsiUskSm/sMmq2bb7rufMadUCgYEA4gaMhjrkfwuv+FworGwyiTGjUBvgLsKn
TejeHVBfgiHI77fC9H5kZBp99NC2MQyjCzVFwLCu6EKQDTbNyB9lDW8xczTor5gQ
N/7dbp1xSHCMoysIM3eBSW+sHa11nbQYl6MikhnAJHfAMYW92bpwuLjsxZE2EDXn
fpFMZtrDko8CgYAXNEqLQPJ1cKuA+082Ggoo8tQvdrCDn2DbvDfzZm+RKaqSUZ8P
6LYXs46NmsYyZh+5ri/WxtWGlyb59cbSmWafqo8UqWg44yrdJqJosEgWBzPdMH5n
MbRdAmC8jO5AKmZz5gV611yfx/hfU5lMHYKvLcakXBMh600oTitsn9O7FQKBgQDL
Ets61rrpMpT97b9VezjEbuauWP1IxfcPVsQJTmchQj2Is2/jv5NvJSY5yTOISjRL
I6fyAkyDvRoz5SNqRFrEgTzKp6TP7y3TQZethKN9VDHngAg0RZDRbBYV6/0ane7i
ft3WqnAp07XISMNUVeBk9zE0KM2MLwI4g09DshW5HQKBgQDItgJgd8fg6Da/mbVy
cetvGJ73BGTprk4TuLLiQtM396TvEGXFLFaX5XYnLjbAJxH/y3hAsVhCOcQK9LX3
te6Bcyom6Oxhoi2KWq5mcA6kBWFwiukIPcZtZMi4o0H74pZxN4u7mCjJhN5wLRPS
/MnhrKIXeGa8BTgX8rlkPQ/3pg==
-----END RSA PRIVATE KEY-----"""
ALIPAY_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0TzZRV6eVQ5bCjtDP+Q4
p4vzacH4+M6W8+DmYDLqBSFh/DiTsOX8qhitimemXlSj7OuGYZp5oRKjVy67zUXZ
YSVjrc6X3skmYkmzD0KBQ1X5Jqc0R7HPveAhQwceBixzubfOzjpSoTLjoxtbjXjM
QZH8PdHIY2B5YRWkL1ffM0xpa62Zh1oLDeEj9TZZnBInudfRwluQ6N0mmvSdCU2K
2/ASBM+iWnJtHP491ehyLaD6IauGWt+CDxd99fnvoNDnyjh6YiCv6xlXUC9zeEbu
ua/Bdh29FOnfB7SZ8MJ35vHZ7+Mw/40gOMQiV7KbOsUFspWu0r3CcuFy4WCYDsmX
+wIDAQAB
-----END PUBLIC KEY-----"""
