# Generated by Django 6.0.2 on 2026-03-06 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0002_load_csl_2026_teams"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0, verbose_name="胜点")),
                (
                    "matches_played",
                    models.PositiveIntegerField(default=0, verbose_name="场次"),
                ),
                ("wins", models.PositiveIntegerField(default=0, verbose_name="胜")),
                ("draws", models.PositiveIntegerField(default=0, verbose_name="平")),
                ("losses", models.PositiveIntegerField(default=0, verbose_name="负")),
                (
                    "goals_for",
                    models.PositiveIntegerField(default=0, verbose_name="进球"),
                ),
                (
                    "goals_against",
                    models.PositiveIntegerField(default=0, verbose_name="失球"),
                ),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing",
                        to="teams.team",
                        verbose_name="球队",
                    ),
                ),
            ],
            options={
                "verbose_name": "积分",
                "verbose_name_plural": "积分榜",
                "ordering": ["-points", "-goals_for", "goals_against"],
            },
        ),
    ]
