# Generated by Django 6.0.2 on 2026-03-06 02:40

from django.db import migrations


def create_standings(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    TeamStanding = apps.get_model("leagues", "TeamStanding")
    for team in Team.objects.all():
        TeamStanding.objects.get_or_create(team=team)


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0001_initial"),
        ("teams", "0002_load_csl_2026_teams"),
    ]

    operations = [
        migrations.RunPython(create_standings, migrations.RunPython.noop),
    ]
