# Generated by Django 6.0.2 on 2026-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0002_load_initial_standings"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamstanding",
            name="assists",
            field=models.PositiveIntegerField(default=0, verbose_name="助攻"),
        ),
        migrations.AddField(
            model_name="teamstanding",
            name="corners",
            field=models.PositiveIntegerField(default=0, verbose_name="角球"),
        ),
        migrations.AddField(
            model_name="teamstanding",
            name="fouls",
            field=models.PositiveIntegerField(default=0, verbose_name="犯规"),
        ),
        migrations.AddField(
            model_name="teamstanding",
            name="offsides",
            field=models.PositiveIntegerField(default=0, verbose_name="越位"),
        ),
        migrations.AddField(
            model_name="teamstanding",
            name="passes",
            field=models.PositiveIntegerField(default=0, verbose_name="传球"),
        ),
        migrations.AddField(
            model_name="teamstanding",
            name="penalties",
            field=models.PositiveIntegerField(default=0, verbose_name="点球"),
        ),
        migrations.AddField(
            model_name="teamstanding",
            name="red_cards",
            field=models.PositiveIntegerField(default=0, verbose_name="红牌"),
        ),
        migrations.AddField(
            model_name="teamstanding",
            name="saves",
            field=models.PositiveIntegerField(default=0, verbose_name="扑救"),
        ),
        migrations.AddField(
            model_name="teamstanding",
            name="shots",
            field=models.PositiveIntegerField(default=0, verbose_name="射门"),
        ),
        migrations.AddField(
            model_name="teamstanding",
            name="shots_on_target",
            field=models.PositiveIntegerField(default=0, verbose_name="射正"),
        ),
        migrations.AddField(
            model_name="teamstanding",
            name="yellow_cards",
            field=models.PositiveIntegerField(default=0, verbose_name="黄牌"),
        ),
    ]
