# Generated by Django 6.0.2 on 2026-03-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0003_teamstanding_assists_teamstanding_corners_and_more"),
        ("teams", "0004_player_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamstanding",
            name="year",
            field=models.PositiveIntegerField(default=2026, verbose_name="年份"),
        ),
        migrations.AlterField(
            model_name="teamstanding",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standings",
                to="teams.team",
                verbose_name="球队",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamstanding",
            unique_together={("team", "year")},
        ),
    ]
